# =========================================
# Stage: Development (Vite React.js App)
# =========================================
ARG NODE_VERSION=24.14.1
 
FROM node:${NODE_VERSION} AS dev
 
# Set working directory inside the container
WORKDIR /app

# Use the Yarn version expected by the repo
RUN corepack enable
 
# Copy package files
COPY package.json yarn.lock ./
 
# Install dependencies
RUN --mount=type=cache,target=/root/.yarn/berry/cache \
	yarn install --immutable
 
# Copy rest of the source code
COPY . .
 
 
# Ensure the "node" user owns the application files
RUN chown -R node:node /app
 
 
# Switch to the built-in non-root "node" user
USER node
 
 
# Expose Vite dev server port
EXPOSE 5173
 
# Run Vite in dev mode, accessible outside the container
CMD ["yarn", "dev", "--host", "0.0.0.0"]